USE `timelog`;
create table task (
	id INT,
	user_name VARCHAR(50),
	project_name VARCHAR(150),
	`date` DATE,
	hours INT,
	`desc` TEXT
)default charset=utf8;
insert into task (id, user_name, project_name, `date`, hours, `desc`) values (1, 'Mathe', 'Internap Corporation', '2019-03-05 13:33:55', 4, 'Nulla tempus.');
insert into task (id, user_name, project_name, `date`, hours, `desc`) values (2, 'Samantha', 'Stamps.com Inc.', '2019-03-07 22:35:09', 4, 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.');
insert into task (id, user_name, project_name, `date`, hours, `desc`) values (3, 'Mia', 'Pacific Special Acquisition Corp.', '2019-03-07 15:20:26', 1, 'Vivamus in felis eu sapien cursus vestibulum.');
insert into task (id, user_name, project_name, `date`, hours, `desc`) values (4, 'Robers', 'Honeywell International Inc.', '2019-03-04 20:24:56', 2, 'Sed sagittis.');
insert into task (id, user_name, project_name, `date`, hours, `desc`) values (5, 'Sharl', 'OFG Bancorp', '2019-03-01 22:25:10', 3, 'Pellentesque eget nunc.');
insert into task (id, user_name, project_name, `date`, hours, `desc`) values (6, 'Kandy', 'PIMCO Dynamic Credit and Mortgage Income Fund', '2019-03-04 22:44:43', 1, 'Fusce consequat.');
insert into task (id, user_name, project_name, `date`, hours, `desc`) values (7, 'Evaleen', 'Upland Software, Inc.', '2019-03-03 09:16:19', 1, 'Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.');
insert into task (id, user_name, project_name, `date`, hours, `desc`) values (8, 'Fraser', 'Cesca Therapeutics Inc.', '2019-03-03 01:07:27', 1, 'Suspendisse ornare consequat lectus.');
insert into task (id, user_name, project_name, `date`, hours, `desc`) values (9, 'Fred', 'Blackrock MuniYield Fund, Inc.', '2019-03-02 14:03:15', 2, 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.');
insert into task (id, user_name, project_name, `date`, hours, `desc`) values (10, 'Travers', 'Benitec Biopharma Limited', '2019-03-08 22:20:11', 1, 'Integer ac leo.');
insert into task (id, user_name, project_name, `date`, hours, `desc`) values (11, 'Jillane', 'Entergy New Orleans, Inc.', '2019-03-01 00:49:09', 2, 'Curabitur convallis.');
insert into task (id, user_name, project_name, `date`, hours, `desc`) values (12, 'Lexine', 'Becton, Dickinson and Company', '2019-03-03 18:10:29', 4, 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.');
insert into task (id, user_name, project_name, `date`, hours, `desc`) values (13, 'Catlin', 'Premier Financial Bancorp, Inc.', '2019-03-06 21:21:28', 1, 'Curabitur gravida nisi at nibh.');
insert into task (id, user_name, project_name, `date`, hours, `desc`) values (14, 'Lowe', 'CRH PLC', '2019-03-02 02:51:23', 1, 'Vivamus vestibulum sagittis sapien.');
insert into task (id, user_name, project_name, `date`, hours, `desc`) values (15, 'Libbey', 'Central Federal Corporation', '2019-03-05 14:33:53', 4, 'Nullam sit amet turpis elementum ligula vehicula consequat.');
insert into task (id, user_name, project_name, `date`, hours, `desc`) values (16, 'Ailyn', 'Landmark Infrastructure Partners LP', '2019-03-07 10:22:10', 2, 'Aenean auctor gravida sem.');
insert into task (id, user_name, project_name, `date`, hours, `desc`) values (17, 'Shep', 'Sundance Energy Australia Limited', '2019-03-03 01:50:53', 3, 'Mauris ullamcorper purus sit amet nulla.');
insert into task (id, user_name, project_name, `date`, hours, `desc`) values (18, 'Agretha', 'STRATS Trust', '2019-03-07 22:16:33', 3, 'Mauris lacinia sapien quis libero.');
insert into task (id, user_name, project_name, `date`, hours, `desc`) values (19, 'Garrot', 'Otelco Inc.', '2019-03-08 13:43:08', 2, 'Pellentesque at nulla.');
insert into task (id, user_name, project_name, `date`, hours, `desc`) values (20, 'Virgie', 'MercadoLibre, Inc.', '2019-03-08 00:03:03', 1, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.');
insert into task (id, user_name, project_name, `date`, hours, `desc`) values (21, 'Conrade', 'Alarm.com Holdings, Inc.', '2019-03-01 06:16:23', 3, 'Aliquam erat volutpat.');
insert into task (id, user_name, project_name, `date`, hours, `desc`) values (22, 'Ulric', 'Teleflex Incorporated', '2019-03-03 15:25:50', 3, 'Nulla tellus.');
insert into task (id, user_name, project_name, `date`, hours, `desc`) values (23, 'Devina', 'BlueStar TA-BIGITech Israel Technology ETF', '2019-03-03 03:44:28', 3, 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.');
insert into task (id, user_name, project_name, `date`, hours, `desc`) values (24, 'Sherwood', 'Cathay General Bancorp', '2019-03-04 03:13:41', 4, 'Integer non velit.');
insert into task (id, user_name, project_name, `date`, hours, `desc`) values (25, 'Tuck', 'Corbus Pharmaceuticals Holdings, Inc.', '2019-03-06 13:20:29', 4, 'Donec quis orci eget orci vehicula condimentum.');
insert into task (id, user_name, project_name, `date`, hours, `desc`) values (26, 'Deanna', 'Inspired Entertainment, Inc.', '2019-03-06 14:14:27', 3, 'Vivamus vel nulla eget eros elementum pellentesque.');
insert into task (id, user_name, project_name, `date`, hours, `desc`) values (27, 'Harrison', 'Cross Timbers Royalty Trust', '2019-03-06 08:55:53', 3, 'Quisque ut erat.');
insert into task (id, user_name, project_name, `date`, hours, `desc`) values (28, 'Cherish', 'Navient Corporation', '2019-03-03 16:02:38', 2, 'Integer tincidunt ante vel ipsum.');
insert into task (id, user_name, project_name, `date`, hours, `desc`) values (29, 'Giustino', 'Viking Therapeutics, Inc.', '2019-03-04 14:30:45', 2, 'In hac habitasse platea dictumst.');
insert into task (id, user_name, project_name, `date`, hours, `desc`) values (30, 'Kailey', 'Nuveen Quality Municipal Income Fund', '2019-03-07 07:24:18', 4, 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.');
insert into task (id, user_name, project_name, `date`, hours, `desc`) values (31, 'Eda', 'Nuveen Tax-Advantaged Dividend Growth Fund', '2019-03-05 03:59:06', 3, 'In eleifend quam a odio.');
insert into task (id, user_name, project_name, `date`, hours, `desc`) values (32, 'Anders', 'Citigroup Inc.', '2019-03-03 19:00:34', 1, 'Vivamus in felis eu sapien cursus vestibulum.');
insert into task (id, user_name, project_name, `date`, hours, `desc`) values (33, 'Adham', 'Eaton Vance Corporation', '2019-03-03 04:36:56', 1, 'Aliquam sit amet diam in magna bibendum imperdiet.');
insert into task (id, user_name, project_name, `date`, hours, `desc`) values (34, 'Sandi', 'MasTec, Inc.', '2019-03-01 01:39:30', 2, 'Nam nulla.');
insert into task (id, user_name, project_name, `date`, hours, `desc`) values (35, 'Brade', 'Latin American Discovery Fund, Inc. (The)', '2019-03-08 14:16:17', 2, 'Vivamus in felis eu sapien cursus vestibulum.');
insert into task (id, user_name, project_name, `date`, hours, `desc`) values (36, 'Sharron', 'PPlus Trust', '2019-03-07 19:25:03', 4, 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.');
insert into task (id, user_name, project_name, `date`, hours, `desc`) values (37, 'Alec', 'Baker Hughes Incorporated', '2019-03-07 14:28:10', 4, 'Proin eu mi.');
insert into task (id, user_name, project_name, `date`, hours, `desc`) values (38, 'Nefen', 'Nuveen AMT-Free Quality Municipal Income Fund', '2019-03-06 22:28:57', 3, 'Praesent blandit lacinia erat.');
insert into task (id, user_name, project_name, `date`, hours, `desc`) values (39, 'Cristie', 'Corbus Pharmaceuticals Holdings, Inc.', '2019-03-03 15:17:01', 2, 'Integer tincidunt ante vel ipsum.');
insert into task (id, user_name, project_name, `date`, hours, `desc`) values (40, 'Cleopatra', 'Quanex Building Products Corporation', '2019-03-08 00:37:03', 3, 'Curabitur in libero ut massa volutpat convallis.');
insert into task (id, user_name, project_name, `date`, hours, `desc`) values (41, 'Luce', 'Forterra, Inc.', '2019-03-01 06:15:17', 2, 'Duis mattis egestas metus.');
insert into task (id, user_name, project_name, `date`, hours, `desc`) values (42, 'Fanya', 'Amerco', '2019-03-05 22:50:41', 3, 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.');
insert into task (id, user_name, project_name, `date`, hours, `desc`) values (43, 'Malia', 'Nuveen Floating Rate Income Fund', '2019-03-07 03:30:05', 4, 'Donec ut mauris eget massa tempor convallis.');
insert into task (id, user_name, project_name, `date`, hours, `desc`) values (44, 'Dewitt', 'Netflix, Inc.', '2019-03-04 20:33:13', 1, 'Integer tincidunt ante vel ipsum.');
insert into task (id, user_name, project_name, `date`, hours, `desc`) values (45, 'Karolina', 'Six Flags Entertainment Corporation New', '2019-03-08 09:20:25', 1, 'Fusce consequat.');
insert into task (id, user_name, project_name, `date`, hours, `desc`) values (46, 'Kevina', 'Adient plc', '2019-03-01 16:58:12', 2, 'Nunc nisl.');
insert into task (id, user_name, project_name, `date`, hours, `desc`) values (47, 'Cyndi', 'Visa Inc.', '2019-03-03 03:50:58', 4, 'Praesent blandit.');
insert into task (id, user_name, project_name, `date`, hours, `desc`) values (48, 'Colette', 'Innoviva, Inc.', '2019-03-05 04:04:38', 2, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.');
insert into task (id, user_name, project_name, `date`, hours, `desc`) values (49, 'Adrienne', 'Endurance International Group Holdings, Inc.', '2019-03-08 21:21:06', 1, 'Nullam sit amet turpis elementum ligula vehicula consequat.');
insert into task (id, user_name, project_name, `date`, hours, `desc`) values (50, 'Saloma', 'Medigus Ltd.', '2019-03-08 17:50:29', 4, 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.');
insert into task (id, user_name, project_name, `date`, hours, `desc`) values (51, 'Eolande', 'Vmware, Inc.', '2019-03-07 07:41:38', 3, 'Aenean lectus.');
insert into task (id, user_name, project_name, `date`, hours, `desc`) values (52, 'Godard', 'Pimco Corporate & Income Stategy Fund', '2019-03-03 21:23:53', 2, 'Nulla justo.');
insert into task (id, user_name, project_name, `date`, hours, `desc`) values (53, 'Lowell', 'Aegean Marine Petroleum Network Inc.', '2019-03-04 17:22:11', 1, 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.');
insert into task (id, user_name, project_name, `date`, hours, `desc`) values (54, 'Erinn', 'Heartland Financial USA, Inc.', '2019-03-01 15:28:08', 3, 'In hac habitasse platea dictumst.');
insert into task (id, user_name, project_name, `date`, hours, `desc`) values (55, 'Winfield', 'voxeljet AG', '2019-03-04 05:38:32', 3, 'Curabitur convallis.');
insert into task (id, user_name, project_name, `date`, hours, `desc`) values (56, 'Hildagarde', 'MUELLER WATER PRODUCTS', '2019-03-04 08:18:02', 1, 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.');
insert into task (id, user_name, project_name, `date`, hours, `desc`) values (57, 'Dennie', 'WSFS Financial Corporation', '2019-03-07 19:14:08', 2, 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla.');
insert into task (id, user_name, project_name, `date`, hours, `desc`) values (58, 'Gracie', 'Avianca Holdings S.A.', '2019-03-07 18:22:07', 4, 'Nulla facilisi.');
insert into task (id, user_name, project_name, `date`, hours, `desc`) values (59, 'Doreen', 'Charles & Colvard Ltd', '2019-03-01 11:08:41', 1, 'Morbi a ipsum.');
insert into task (id, user_name, project_name, `date`, hours, `desc`) values (60, 'Marius', 'Orchid Island Capital, Inc.', '2019-03-06 15:51:22', 1, 'Maecenas ut massa quis augue luctus tincidunt.');
insert into task (id, user_name, project_name, `date`, hours, `desc`) values (61, 'Aurlie', 'Biostage, Inc.', '2019-03-04 20:00:42', 3, 'Nullam molestie nibh in lectus.');
insert into task (id, user_name, project_name, `date`, hours, `desc`) values (62, 'Dory', 'HV Bancorp, Inc.', '2019-03-06 16:27:19', 3, 'Fusce consequat.');
insert into task (id, user_name, project_name, `date`, hours, `desc`) values (63, 'Yulma', 'National Grid Transco, PLC', '2019-03-08 22:22:05', 1, 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.');
insert into task (id, user_name, project_name, `date`, hours, `desc`) values (64, 'Hazel', 'Juno Therapeutics, Inc.', '2019-03-08 06:13:12', 4, 'In quis justo.');
insert into task (id, user_name, project_name, `date`, hours, `desc`) values (65, 'Annamaria', 'Cogint, Inc.', '2019-03-02 11:33:51', 1, 'Morbi a ipsum.');
insert into task (id, user_name, project_name, `date`, hours, `desc`) values (66, 'Dosi', 'El Paso Corporation', '2019-03-01 07:27:55', 3, 'Maecenas tincidunt lacus at velit.');
insert into task (id, user_name, project_name, `date`, hours, `desc`) values (67, 'Genvieve', 'Microchip Technology Incorporated', '2019-03-06 00:10:28', 3, 'Morbi vel lectus in quam fringilla rhoncus.');
insert into task (id, user_name, project_name, `date`, hours, `desc`) values (68, 'Fred', 'First Trust/Aberdeen Emerging Opportunity Fund', '2019-03-04 05:11:54', 3, 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.');
insert into task (id, user_name, project_name, `date`, hours, `desc`) values (69, 'Pattin', 'Caesarstone Ltd.', '2019-03-04 20:31:50', 4, 'Maecenas ut massa quis augue luctus tincidunt.');
insert into task (id, user_name, project_name, `date`, hours, `desc`) values (70, 'Kailey', 'Cohen & Steers Select Preferred and Income Fund, Inc.', '2019-03-06 22:16:55', 3, 'Nulla mollis molestie lorem.');
insert into task (id, user_name, project_name, `date`, hours, `desc`) values (71, 'Tito', 'Akoustis Technologies, Inc.', '2019-03-02 16:28:42', 2, 'Maecenas ut massa quis augue luctus tincidunt.');
insert into task (id, user_name, project_name, `date`, hours, `desc`) values (72, 'Hamil', 'M I Acquisitions, Inc.', '2019-03-07 18:43:24', 3, 'Phasellus in felis.');
insert into task (id, user_name, project_name, `date`, hours, `desc`) values (73, 'Hedwig', 'National Holdings Corporation', '2019-03-07 15:21:29', 1, 'Suspendisse potenti.');
insert into task (id, user_name, project_name, `date`, hours, `desc`) values (74, 'Jere', 'Marrone Bio Innovations, Inc.', '2019-03-06 06:46:45', 4, 'Aenean auctor gravida sem.');
insert into task (id, user_name, project_name, `date`, hours, `desc`) values (75, 'Sergeant', 'Urban One, Inc. ', '2019-03-04 20:38:49', 3, 'Vivamus tortor.');
insert into task (id, user_name, project_name, `date`, hours, `desc`) values (76, 'Lorianna', 'Nexstar Media Group, Inc.', '2019-03-05 22:39:48', 4, 'Vivamus vel nulla eget eros elementum pellentesque.');
insert into task (id, user_name, project_name, `date`, hours, `desc`) values (77, 'Kingsly', 'Torchmark Corporation', '2019-03-06 19:18:27', 1, 'Praesent lectus.');
insert into task (id, user_name, project_name, `date`, hours, `desc`) values (78, 'Tamqrah', 'iShares GNMA Bond ETF', '2019-03-06 01:56:49', 4, 'Fusce consequat.');
insert into task (id, user_name, project_name, `date`, hours, `desc`) values (79, 'Minor', 'Novo Nordisk A/S', '2019-03-01 10:03:17', 3, 'Nulla suscipit ligula in lacus.');
insert into task (id, user_name, project_name, `date`, hours, `desc`) values (80, 'Olympie', 'MabVax Therapeutics Holdings, Inc.', '2019-03-06 04:10:50', 4, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.');
insert into task (id, user_name, project_name, `date`, hours, `desc`) values (81, 'Uriah', 'TEGNA Inc.', '2019-03-06 23:53:42', 1, 'In eleifend quam a odio.');
insert into task (id, user_name, project_name, `date`, hours, `desc`) values (82, 'Winifield', 'VALE S.A.', '2019-03-08 23:08:49', 1, 'Nulla tempus.');
insert into task (id, user_name, project_name, `date`, hours, `desc`) values (83, 'Osbourne', 'Hawaiian Telcom Holdco, Inc.', '2019-03-04 04:26:01', 2, 'Curabitur at ipsum ac tellus semper interdum.');
insert into task (id, user_name, project_name, `date`, hours, `desc`) values (84, 'Theodore', 'Renesola Ltd.', '2019-03-07 19:49:28', 3, 'Curabitur gravida nisi at nibh.');
insert into task (id, user_name, project_name, `date`, hours, `desc`) values (85, 'Dede', 'MSA Safety Incorporporated', '2019-03-06 09:35:57', 1, 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.');
insert into task (id, user_name, project_name, `date`, hours, `desc`) values (86, 'Shirline', 'Pembina Pipeline Corp.', '2019-03-03 07:31:25', 1, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.');
insert into task (id, user_name, project_name, `date`, hours, `desc`) values (87, 'Byrle', 'First Trust Emerging Markets AlphaDEX Fund', '2019-03-08 22:26:12', 1, 'Fusce consequat.');
insert into task (id, user_name, project_name, `date`, hours, `desc`) values (88, 'Jaquenette', 'New Residential Investment Corp.', '2019-03-02 00:06:47', 4, 'Sed ante.');
insert into task (id, user_name, project_name, `date`, hours, `desc`) values (89, 'Trixy', 'EMC Insurance Group Inc.', '2019-03-08 09:36:28', 1, 'Nam tristique tortor eu pede.');
insert into task (id, user_name, project_name, `date`, hours, `desc`) values (90, 'Rochette', 'Xencor, Inc.', '2019-03-02 07:48:19', 3, 'Curabitur convallis.');
insert into task (id, user_name, project_name, `date`, hours, `desc`) values (91, 'Rufus', 'TOR Minerals International Inc', '2019-03-05 16:06:25', 2, 'Nunc purus.');
insert into task (id, user_name, project_name, `date`, hours, `desc`) values (92, 'Aksel', 'FirstService Corporation', '2019-03-02 16:12:18', 3, 'Curabitur at ipsum ac tellus semper interdum.');
insert into task (id, user_name, project_name, `date`, hours, `desc`) values (93, 'Kurt', 'Conyers Park Acquisition Corp.', '2019-03-06 02:02:17', 3, 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.');
insert into task (id, user_name, project_name, `date`, hours, `desc`) values (94, 'Alisha', 'Marrone Bio Innovations, Inc.', '2019-03-08 01:11:42', 1, 'Aliquam non mauris.');
insert into task (id, user_name, project_name, `date`, hours, `desc`) values (95, 'Leonidas', 'ImmuCell Corporation', '2019-03-08 05:04:49', 3, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.');
insert into task (id, user_name, project_name, `date`, hours, `desc`) values (96, 'Cass', 'Liberty All-Star Equity Fund', '2019-03-08 17:02:05', 1, 'Proin eu mi.');
insert into task (id, user_name, project_name, `date`, hours, `desc`) values (97, 'Delmar', 'The Long-Term Care ETF', '2019-03-07 00:30:58', 1, 'Integer a nibh.');
insert into task (id, user_name, project_name, `date`, hours, `desc`) values (98, 'Dionysus', 'Nuveen Select Maturities Municipal Fund', '2019-03-01 18:02:55', 3, 'Proin at turpis a pede posuere nonummy.');
insert into task (id, user_name, project_name, `date`, hours, `desc`) values (99, 'Jackqueline', 'Avadel Pharmaceuticals plc', '2019-03-05 13:06:16', 2, 'Donec quis orci eget orci vehicula condimentum.');
insert into task (id, user_name, project_name, `date`, hours, `desc`) values (100, 'Portia', 'WPX Energy, Inc.', '2019-03-03 19:55:51', 3, 'Curabitur in libero ut massa volutpat convallis.');
